on: [push, pull_request]
name: Quality assurance
jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: PHPStan
              uses: "docker://oskarstark/phpstan-ga"
              with:
                  args: analyse
